[package]
name = "stealth-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
hpke = "0.13.0"
k256 = "0.13.4"
ed25519-dalek = "2.1.1"
ecies = "0.2.9"
rand_core = "0.9.3"
thiserror = "2.0.12"
x25519-dalek = "2.0.1"
rand = "0.9.0"